# This file is generated by scripts/publish-homebrew.mjs on every Optimus
# release — do not edit by hand, changes will be overwritten on the next
# release.
class Optimus < Formula
  desc "Optimus — an agentic coding CLI that reads/writes files, runs shell commands, and works on your project autonomously via an LLM."
  homepage "https://github.com/brightbraincoder/optimus-releases"
  version "0.289.2"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.2/optimus-v0.289.2-macos-arm64"
      sha256 "0d27fe34bd943ba3ab0742669950339e37c1121956de9ef1d4f7b2aba69adb2d"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.2/optimus-v0.289.2-macos-x64"
      sha256 "5c57b7cade98429a657e47f704e154864b5a4c59d2c7feb016a9f82e8d8c1c32"
    end

  end

  on_linux do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.2/optimus-v0.289.2-linux-arm64"
      sha256 "abd6e66936893fffb0deb48e91f648b2a4cd5578c0053d20ef194f2818c3f0b5"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.2/optimus-v0.289.2-linux-x64"
      sha256 "a0e15ff03f4635b80cdaf1f4473159a00978930c9543121424088921c1461de4"
    end

  end

  def install
    downloaded = Dir["optimus-*"].first
    bin.install downloaded => "optimus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optimus --version")
  end
end
