# This file is generated by scripts/publish-homebrew.mjs on every Optimus
# release — do not edit by hand, changes will be overwritten on the next
# release.
class OptimusCli < Formula
  desc "Optimus — an agentic coding CLI that reads/writes files, runs shell commands, and works on your project autonomously via an LLM."
  homepage "https://github.com/brightbraincoder/optimus-releases"
  version "0.338.0-alpha.110"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.110/optimus-cli-v0.338.0-macos-arm64"
      sha256 "bc2a6b49ff68ab3024f923e3c7be11bfa8b19c2c3e4669da60fef0ae548ad13d"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.110/optimus-cli-v0.338.0-macos-x64"
      sha256 "7bc9b518eb660579fe4af0e42b4800759216bc7d4025400253bdf56058620f48"
    end

  end

  on_linux do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.110/optimus-cli-v0.338.0-linux-arm64"
      sha256 "1cfa4675797fb398c3e5bb096b387de53b57a564beb6928c0465ce7bbff89b47"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.110/optimus-cli-v0.338.0-linux-x64"
      sha256 "5ea340cc37f1237e2595804fb37d86556269c143fc841ef739f0329164d7c9d9"
    end

  end

  def install
    downloaded = Dir["optimus-cli-*"].first
    bin.install downloaded => "optimus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optimus --version")
  end
end
