# This file is generated by scripts/publish-homebrew.mjs on every Optimus
# release — do not edit by hand, changes will be overwritten on the next
# release.
class OptimusCli < Formula
  desc "Optimus — an agentic coding CLI that reads/writes files, runs shell commands, and works on your project autonomously via an LLM."
  homepage "https://github.com/brightbraincoder/optimus-releases"
  version "0.338.0-alpha.114"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.114/optimus-cli-v0.338.0-alpha.114-macos-arm64"
      sha256 "1bf6a8691c53c269c41750b790db7b2d33dee9551aaed5df669fd8b7b0c23f56"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.114/optimus-cli-v0.338.0-alpha.114-macos-x64"
      sha256 "152bf117e8e4a3ff2d3c89b07ebe4a5560c47f21abc8738cdc9ce69e7d0f11d0"
    end

  end

  on_linux do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.114/optimus-cli-v0.338.0-alpha.114-linux-arm64"
      sha256 "3db90fb0f9d516db74721323c8fdd3358c736a8c531895d6fe0ffd5bed3a9c9f"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.338.0-alpha.114/optimus-cli-v0.338.0-alpha.114-linux-x64"
      sha256 "6d2c2045e6c24e42419e3a4b12cf6e7c311423b5e19a16dd362cf6b8688c0888"
    end

  end

  def install
    downloaded = Dir["optimus-cli-*"].first
    bin.install downloaded => "optimus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optimus --version")
  end
end
