# This file is generated by scripts/publish-homebrew.mjs on every Optimus
# release — do not edit by hand, changes will be overwritten on the next
# release.
class OptimusCli < Formula
  desc "Optimus — an agentic coding CLI that reads/writes files, runs shell commands, and works on your project autonomously via an LLM."
  homepage "https://github.com/brightbraincoder/optimus-releases"
  version "0.334.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.334.0/optimus-cli-v0.334.0-macos-arm64"
      sha256 "51f853ef85133bade226561771412cebccd065d6185b9c1e301cd7e8485389db"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.334.0/optimus-cli-v0.334.0-macos-x64"
      sha256 "82f1a3717be76fa7b8ad5f831be3dd1403a3d406028dc39f826cd7eefe29fb10"
    end

  end

  on_linux do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.334.0/optimus-cli-v0.334.0-linux-arm64"
      sha256 "0bc2fdd2cf003afa78aa24bf1b229fc393ab6df75d74bda80656a8e0031caae6"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.334.0/optimus-cli-v0.334.0-linux-x64"
      sha256 "162b998f6aab1d252340386cae533f3dc36d61aad2088a5e635eddff6fdd5df1"
    end

  end

  def install
    downloaded = Dir["optimus-cli-*"].first
    bin.install downloaded => "optimus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optimus --version")
  end
end
