# This file is generated by scripts/publish-homebrew.mjs on every Optimus
# release — do not edit by hand, changes will be overwritten on the next
# release.
class Optimus < Formula
  desc "Optimus — an agentic coding CLI that reads/writes files, runs shell commands, and works on your project autonomously via an LLM."
  homepage "https://github.com/brightbraincoder/optimus-releases"
  version "0.289.3"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.3/optimus-v0.289.3-macos-arm64"
      sha256 "9c241a9897100eddb7d36d108c8eede935e6cc73eb96bb826ef625d0a53fa723"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.3/optimus-v0.289.3-macos-x64"
      sha256 "017152fdb28510b8eaa35578ffcece645ac9c98b2c36f834a01085e0505608ce"
    end

  end

  on_linux do
    on_arm do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.3/optimus-v0.289.3-linux-arm64"
      sha256 "fa37e00d4df9b33ee8af430601865da66e382f7faeb093b3b101b3edbd9457a3"
    end
    on_intel do
      url "https://github.com/brightbraincoder/optimus-releases/releases/download/v0.289.3/optimus-v0.289.3-linux-x64"
      sha256 "6093b75092caf02148d361a116f335eb4bdbd183f3015351103c6dbb64aff2b3"
    end

  end

  def install
    downloaded = Dir["optimus-*"].first
    bin.install downloaded => "optimus"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optimus --version")
  end
end
